# Generated by Django 3.1.2 on 2020-10-21 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_id', models.CharField(max_length=255, verbose_name='Original Id')),
                ('cost', models.PositiveIntegerField(verbose_name='Cost')),
                ('idempotency_token', models.CharField(max_length=255, verbose_name='Idempotency Token')),
                ('items', models.JSONField(default=dict, verbose_name='Items')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.terminal')),
            ],
        ),
    ]
