# Generated by Django 3.1.2 on 2020-10-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Original Id'),
        ),
    ]
