# Generated by Django 3.1.2 on 2020-10-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20201021_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idempotency_token',
            field=models.CharField(max_length=255, null=True, verbose_name='Idempotency Token'),
        ),
    ]
